replicaCount: 1

image:
  repository: aviosi479/sb-chat-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: web
  portName: http

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: sb-chat-ui.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sb-chat-ui-tls
      hosts:
        - sb-chat-ui.example.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  api:
    url: "http://sb-agent-portal:80"  # Default internal API URL

env:
  NODE_ENV: production
  PORT: 5173

probes:
  readiness:
    initialDelaySeconds: 50
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 50
    periodSeconds: 20 